version: '3.8'

services:
  app:
    build: ./backend
    env_file:
      - .env
    environment:
      SPRING_APPLICATION_JSON: '{
              "spring.data.mongodb.uri" : "mongodb://$MONGODB_USER:$MONGODB_PASSWORD@db:$MONGODB_PORT/$MONGODB_DATABASE?authSource=admin"
            }'
    ports:
      - "127.0.0.1:8080:8080"
    depends_on:
      - db
  db:
    image: mongo:6.0
    env_file:
      - .env
    environment:
      - 'MONGO_INITDB_DATABASE=$MONGODB_DATABASE'
      - 'MONGO_INITDB_ROOT_PASSWORD=$MONGODB_PASSWORD'
      - 'MONGO_INITDB_ROOT_USERNAME=$MONGODB_USER'
    volumes:
      - mongo_data:/data/db
volumes:
  mongo_data:

